// Command genrpc writes internal/rpc/client/service_gen.go: a Service with
// exactly app.Service's methods, each forwarding the call to the daemon,
// and registering the Wails binding ID app.Service's method has, so the
// frontend's generated bindings call the proxy unchanged.
//
//	go generate ./internal/rpc/client/
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"hash/fnv"
	"log"
	"os"
	"path"
	"reflect"
	"slices"
	"sort"
	"strings"

	"github.com/hashcott/ghostline/internal/app"
)

const appService = "github.com/hashcott/ghostline/internal/app.Service"

func main() {
	out := flag.String("out", "service_gen.go", "file to write")
	flag.Parse()
	src, err := render(appMethods(), defaultSkip())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
}

// defaultSkip lists the methods written by hand in the client package.
func defaultSkip() map[string]bool {
	return map[string]bool{"SetMode": true, "GetSnapshot": true, "ServiceInstall": true, "InstallService": true, "StartService": true, "ReportIssueURL": true}
}

// appMethods are app.Service's exported methods, sorted by name.
func appMethods() []reflect.Method {
	t := reflect.TypeOf(&app.Service{})
	ms := make([]reflect.Method, t.NumMethod())
	for i := range ms {
		ms[i] = t.Method(i)
	}
	return ms
}

// bindingID is Wails' ID for an app.Service method: FNV-32a of its
// fully qualified name.
func bindingID(method string) uint32 {
	h := fnv.New32a()
	_, _ = h.Write([]byte(appService + "." + method))
	return h.Sum32()
}

var (
	errorType = reflect.TypeFor[error]()
)

func isCtx(t reflect.Type) bool { return t.PkgPath() == "context" && t.Name() == "Context" }

// imports maps package paths to the names used in the generated file.
type imports map[string]string

func (im imports) name(pkgPath string) string {
	if n, ok := im[pkgPath]; ok {
		return n
	}
	n := path.Base(pkgPath)
	for _, used := range im {
		if used == n {
			n = strings.ReplaceAll(strings.TrimPrefix(pkgPath, "github.com/hashcott/ghostline/internal/"), "/", "")
		}
	}
	im[pkgPath] = n
	return n
}

// expr writes t as Go source.
func (im imports) expr(t reflect.Type) (string, error) {
	if t.Name() != "" {
		if t.PkgPath() == "" {
			return t.Name(), nil // builtin, error
		}
		return im.name(t.PkgPath()) + "." + t.Name(), nil
	}
	switch t.Kind() {
	case reflect.Slice:
		e, err := im.expr(t.Elem())
		return "[]" + e, err
	case reflect.Array:
		e, err := im.expr(t.Elem())
		return fmt.Sprintf("[%d]%s", t.Len(), e), err
	case reflect.Pointer:
		e, err := im.expr(t.Elem())
		return "*" + e, err
	case reflect.Map:
		k, err := im.expr(t.Key())
		if err != nil {
			return "", err
		}
		v, err := im.expr(t.Elem())
		return "map[" + k + "]" + v, err
	case reflect.Interface:
		if t.NumMethod() == 0 {
			return "any", nil
		}
	}
	return "", fmt.Errorf("genrpc: unsupported type %s", t)
}

// render writes the generated file for methods; skip ones are written by
// hand but still get their binding ID.
func render(methods []reflect.Method, skip map[string]bool) ([]byte, error) {
	im := imports{"context": "context", "github.com/wailsapp/wails/v3/pkg/application": "application"}
	var body bytes.Buffer
	for _, m := range methods {
		if skip[m.Name] {
			continue
		}
		if err := renderMethod(&body, im, m); err != nil {
			return nil, err
		}
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by tools/genrpc; DO NOT EDIT.\n\npackage client\n\nimport (\n")
	paths := make([]string, 0, len(im))
	for p := range im {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		if path.Base(p) == im[p] {
			fmt.Fprintf(&b, "\t%q\n", p)
		} else {
			fmt.Fprintf(&b, "\t%s %q\n", im[p], p)
		}
	}
	b.WriteString(")\n\n")
	b.WriteString("// Binding IDs: each method answers the ID Wails gives app.Service's.\nfunc init() {\n")
	for _, m := range methods {
		fmt.Fprintf(&b, "\tapplication.RegisterBindingMethodID((*Service).%s, %d)\n", m.Name, bindingID(m.Name))
	}
	b.WriteString("}\n\n")
	b.Write(body.Bytes())
	return format.Source(b.Bytes())
}

func renderMethod(w *bytes.Buffer, im imports, m reflect.Method) error {
	t := m.Type // receiver first
	var params, args []string
	ctx := "context.Background()"
	for i := 1; i < t.NumIn(); i++ {
		in := t.In(i)
		if i == 1 && isCtx(in) {
			params = append(params, "ctx context.Context")
			ctx = "ctx"
			continue
		}
		e, err := im.expr(in)
		if err != nil {
			return err
		}
		a := fmt.Sprintf("a%d", len(args))
		params = append(params, a+" "+e)
		args = append(args, a)
	}
	var outs []reflect.Type
	hasErr := false
	for i := 0; i < t.NumOut(); i++ {
		outs = append(outs, t.Out(i))
	}
	if n := len(outs); n > 0 && outs[n-1] == errorType {
		hasErr, outs = true, outs[:n-1]
	}
	var results []string
	for _, o := range outs {
		e, err := im.expr(o)
		if err != nil {
			return err
		}
		results = append(results, e)
	}
	sig := slices.Clone(results)
	if hasErr {
		sig = append(sig, "error")
	}
	ret := strings.Join(sig, ", ")
	if len(sig) > 1 {
		ret = "(" + ret + ")"
	}
	callArgs := strings.Join(append([]string{ctx, fmt.Sprintf("%q", m.Name), "%s"}, args...), ", ")
	fmt.Fprintf(w, "func (s *Service) %s(%s) %s {\n", m.Name, strings.Join(params, ", "), ret)
	switch len(outs) {
	case 0:
		if hasErr {
			fmt.Fprintf(w, "\treturn s.call(%s)\n", fmt.Sprintf(callArgs, "nil"))
		} else {
			fmt.Fprintf(w, "\ts.logErr(%q, s.call(%s))\n", m.Name, fmt.Sprintf(callArgs, "nil"))
		}
	case 1:
		fmt.Fprintf(w, "\tvar r %s\n\terr := s.call(%s)\n", results[0], fmt.Sprintf(callArgs, "&r"))
		if hasErr {
			w.WriteString("\treturn r, err\n")
		} else {
			fmt.Fprintf(w, "\ts.logErr(%q, err)\n\treturn r\n", m.Name)
		}
	default:
		var names, ptrs []string
		for i, r := range results {
			fmt.Fprintf(w, "\tvar r%d %s\n", i, r)
			names = append(names, fmt.Sprintf("r%d", i))
			ptrs = append(ptrs, fmt.Sprintf("&r%d", i))
		}
		fmt.Fprintf(w, "\terr := s.callTuple(%s)\n", fmt.Sprintf(strings.Replace(callArgs, "%s", "[]any{%s}", 1), strings.Join(ptrs, ", ")))
		if hasErr {
			fmt.Fprintf(w, "\treturn %s, err\n", strings.Join(names, ", "))
		} else {
			fmt.Fprintf(w, "\ts.logErr(%q, err)\n\treturn %s\n", m.Name, strings.Join(names, ", "))
		}
	}
	w.WriteString("}\n\n")
	return nil
}
