package sysdns

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func newTestResolvConf(t *testing.T) (Backend, string, string) {
	t.Helper()
	dir := t.TempDir()
	data := filepath.Join(dir, "data")
	require.NoError(t, os.MkdirAll(data, 0o700))
	path := filepath.Join(dir, "etc", "resolv.conf")
	require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
	return newResolvConf(path, data, func() error { return nil }, nil), path, data
}

const ispConf = "# from dhcp\nnameserver 192.168.1.1\nnameserver 192.168.1.2\nsearch lan\n"

func TestResolvConf_RoundTripFile(t *testing.T) {
	b, path, _ := newTestResolvConf(t)
	require.NoError(t, os.WriteFile(path, []byte(ispConf), 0o640))
	require.NoError(t, os.Chmod(path, 0o640))
	s, err := b.Snapshot(Selection{})
	require.NoError(t, err)
	require.Equal(t, []string{"192.168.1.1", "192.168.1.2"}, s.Servers())
	require.NoError(t, b.Apply(s, true))
	got, _ := os.ReadFile(path)
	require.Equal(t, "# Generated by Ghostline\nnameserver 127.0.0.1\nnameserver ::1\noptions edns0 trust-ad\n", string(got))
	require.Empty(t, b.Restore(s))
	got, _ = os.ReadFile(path)
	require.Equal(t, ispConf, string(got))
	fi, _ := os.Stat(path)
	require.Equal(t, os.FileMode(0o640), fi.Mode().Perm())
}

// Review Focus 4: resolv.conf is usually a symlink to a stub file.
func TestResolvConf_RestoresSymlink(t *testing.T) {
	b, path, _ := newTestResolvConf(t)
	stub := filepath.Join(filepath.Dir(path), "stub-resolv.conf")
	require.NoError(t, os.WriteFile(stub, []byte("nameserver 127.0.0.53\n"), 0o644))
	require.NoError(t, os.Symlink("stub-resolv.conf", path))
	s, err := b.Snapshot(Selection{})
	require.NoError(t, err)
	require.NoError(t, b.Apply(s, false))
	fi, _ := os.Lstat(path)
	require.True(t, fi.Mode().IsRegular(), "replaced by a file while connected")
	require.Empty(t, b.Restore(s))
	target, err := os.Readlink(path)
	require.NoError(t, err)
	require.Equal(t, "stub-resolv.conf", target)
	got, _ := os.ReadFile(stub)
	require.Equal(t, "nameserver 127.0.0.53\n", string(got), "the stub itself is never touched")
}

func TestResolvConf_ReconcileAdoptsNewOriginal(t *testing.T) {
	b, path, _ := newTestResolvConf(t)
	require.NoError(t, os.WriteFile(path, []byte(ispConf), 0o644))
	s, _ := b.Snapshot(Selection{})
	require.NoError(t, b.Apply(s, false))
	_, _, changes, err := b.Reconcile(s, Selection{})
	require.NoError(t, err)
	require.Empty(t, changes)

	require.NoError(t, os.WriteFile(path, []byte("nameserver 10.0.0.1\n"), 0o644)) // dhcpcd, new network
	next, toApply, changes, err := b.Reconcile(s, Selection{})
	require.NoError(t, err)
	require.Equal(t, []Change{{Target: path}}, changes)
	require.Equal(t, []string{"10.0.0.1"}, next.Servers())
	require.NoError(t, b.Apply(toApply, false))
	require.Empty(t, b.Restore(next))
	got, _ := os.ReadFile(path)
	require.Equal(t, "nameserver 10.0.0.1\n", string(got), "the new network's DNS comes back")
}

// Review Focus 5.
func TestResolvConf_StillOursNeedsMarker(t *testing.T) {
	b, path, _ := newTestResolvConf(t)
	require.NoError(t, os.WriteFile(path, []byte(ispConf), 0o644))
	s, _ := b.Snapshot(Selection{})
	require.True(t, b.StillOurs(s).Empty())
	require.NoError(t, b.Apply(s, false))
	require.Equal(t, s, b.StillOurs(s))
}

func TestResolvConf_RestoreDefault(t *testing.T) {
	b, path, data := newTestResolvConf(t)
	require.NoError(t, os.WriteFile(path, []byte(ispConf), 0o644))
	require.NoError(t, b.RestoreDefault(), "not ours: nothing to do")
	s, _ := b.Snapshot(Selection{})
	require.NoError(t, b.Apply(s, false))
	require.NoError(t, b.RestoreDefault())
	got, _ := os.ReadFile(path)
	require.Equal(t, ispConf, string(got))

	require.NoError(t, b.Apply(s, false))
	require.NoError(t, os.Remove(filepath.Join(data, "resolv.conf.orig")))
	require.Error(t, b.RestoreDefault(), "ours but no saved copy: no guessing")
}
