package sysdns

import (
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/hashcott/ghostline/internal/model"
	"github.com/stretchr/testify/require"
)

type fakeResolved struct {
	links   []model.ResolvedLink
	gone    map[int]bool // links resolved no longer knows
	flushes int
	onSet   func() // called on every SetDefaultRoute
}

func (f *fakeResolved) Running() bool { return true }
func (f *fakeResolved) Links() ([]model.ResolvedLink, error) {
	return append([]model.ResolvedLink(nil), f.links...), nil
}
func (f *fakeResolved) SetDefaultRoute(ifindex int, on bool) error {
	if f.onSet != nil {
		f.onSet()
	}
	if f.gone[ifindex] {
		return errNoSuchLink
	}
	for i := range f.links {
		if f.links[i].IfIndex == ifindex {
			f.links[i].DefaultRoute = on
		}
	}
	return nil
}
func (f *fakeResolved) FlushCaches() error           { f.flushes++; return nil }
func (f *fakeResolved) Watch(func()) (func(), error) { return func() {}, nil }

type fakeUnits struct{ reloads []string }

func (f *fakeUnits) Reload(unit string) error         { f.reloads = append(f.reloads, unit); return nil }
func (f *fakeUnits) Stop(string, time.Duration) error { return nil }

func eth0() model.ResolvedLink {
	return model.ResolvedLink{IfIndex: 2, Name: "eth0", DefaultRoute: true, Servers: []string{"192.168.1.1"}}
}

func TestResolved_ApplyWritesDropInAndClearsDefaultRoute(t *testing.T) {
	dir := t.TempDir()
	r, u := &fakeResolved{links: []model.ResolvedLink{eth0()}}, &fakeUnits{}
	b := newResolved(r, u, dir, nil)
	require.Equal(t, "resolved", b.Name())
	s, err := b.Snapshot(Selection{})
	require.NoError(t, err)
	require.Equal(t, []string{"192.168.1.1"}, s.Servers())
	require.NoError(t, b.Apply(s, true))
	got, err := os.ReadFile(filepath.Join(dir, "ghostline.conf"))
	require.NoError(t, err)
	// No Domains=~.: the global servers already take every query no link's
	// domain claims, and resolved keeps a global ~. after the drop-in is
	// gone and it reloads (root run, systemd 262).
	require.Equal(t, "# Generated by Ghostline\n[Resolve]\nDNS=127.0.0.1 ::1\n", string(got))
	require.Equal(t, []string{"systemd-resolved.service"}, u.reloads)
	require.False(t, r.links[0].DefaultRoute)
}

func TestResolved_RestorePutsBackDefaultRoute(t *testing.T) {
	dir := t.TempDir()
	r, u := &fakeResolved{links: []model.ResolvedLink{eth0()}}, &fakeUnits{}
	b := newResolved(r, u, dir, nil)
	s, _ := b.Snapshot(Selection{})
	require.NoError(t, b.Apply(s, false))
	require.Empty(t, b.Restore(s))
	_, err := os.Stat(filepath.Join(dir, "ghostline.conf"))
	require.True(t, os.IsNotExist(err))
	require.True(t, r.links[0].DefaultRoute)
	require.Len(t, u.reloads, 2)
}

// The links take queries back before the drop-in goes: the other order
// leaves resolved with no DNS route for a moment.
func TestResolved_RestoreResetsDefaultRouteBeforeDropIn(t *testing.T) {
	dir := t.TempDir()
	r, u := &fakeResolved{links: []model.ResolvedLink{eth0()}}, &fakeUnits{}
	b := newResolved(r, u, dir, nil)
	s, _ := b.Snapshot(Selection{})
	require.NoError(t, b.Apply(s, false))
	var dropInThere []bool
	r.onSet = func() {
		_, err := os.Stat(filepath.Join(dir, "ghostline.conf"))
		dropInThere = append(dropInThere, err == nil)
	}
	require.Empty(t, b.Restore(s))
	require.Equal(t, []bool{true}, dropInThere)
}

func TestResolved_ReconcileHandlesNewAndReset(t *testing.T) {
	dir := t.TempDir()
	r, u := &fakeResolved{links: []model.ResolvedLink{eth0()}}, &fakeUnits{}
	b := newResolved(r, u, dir, nil)
	s, _ := b.Snapshot(Selection{})
	require.NoError(t, b.Apply(s, false))

	r.links[0].DefaultRoute = true // networkd pushed it again
	r.links = append(r.links, model.ResolvedLink{IfIndex: 3, Name: "wlan0", DefaultRoute: true, Servers: []string{"10.0.0.1"}})
	next, toApply, changes, err := b.Reconcile(s, Selection{})
	require.NoError(t, err)
	require.ElementsMatch(t, []Change{{Target: "eth0"}, {Target: "wlan0"}}, changes)
	require.Len(t, next.Linux.ResolvedLinks, 2)
	require.True(t, next.Linux.ResolvedLinks[1].DefaultRoute, "wlan0's own value is recorded")
	require.True(t, next.Linux.ResolvedLinks[0].DefaultRoute, "eth0 keeps its value from before Connect")
	require.NoError(t, b.Apply(toApply, false))
	require.False(t, r.links[0].DefaultRoute)
	require.False(t, r.links[1].DefaultRoute)
}

// Review Focus 5.
func TestResolved_StillOursNeedsDropIn(t *testing.T) {
	dir := t.TempDir()
	b := newResolved(&fakeResolved{links: []model.ResolvedLink{eth0()}}, &fakeUnits{}, dir, nil)
	s, _ := b.Snapshot(Selection{})
	require.True(t, b.StillOurs(s).Empty())
	require.NoError(t, b.Apply(s, false))
	require.Equal(t, s, b.StillOurs(s))
}

func TestResolved_RestoreDefaultRemovesOnlyOurDropIn(t *testing.T) {
	dir := t.TempDir()
	foreign := filepath.Join(dir, "corp.conf")
	require.NoError(t, os.WriteFile(foreign, []byte("[Resolve]\nDNS=10.1.1.1\n"), 0o644))
	u := &fakeUnits{}
	b := newResolved(&fakeResolved{}, u, dir, nil)
	require.NoError(t, b.RestoreDefault())
	require.Empty(t, u.reloads, "nothing of ours: no reload")
	require.NoError(t, os.WriteFile(filepath.Join(dir, "ghostline.conf"), []byte("# Generated by Ghostline\n[Resolve]\nDNS=127.0.0.1\n"), 0o644))
	require.NoError(t, b.RestoreDefault())
	_, err := os.Stat(filepath.Join(dir, "ghostline.conf"))
	require.True(t, os.IsNotExist(err))
	_, err = os.Stat(foreign)
	require.NoError(t, err)
	require.Len(t, u.reloads, 1)
}

// Review I1: a link that went away (VPN down, tether unplugged) is not a
// restore failure, and does not stop Ghostline's configuration going back.
func TestResolved_VanishedLinkIsNotAnError(t *testing.T) {
	dir := t.TempDir()
	vpn := model.ResolvedLink{IfIndex: 7, Name: "tun0", DefaultRoute: true, Servers: []string{"10.8.0.1"}}
	r := &fakeResolved{links: []model.ResolvedLink{eth0(), vpn}}
	b := newResolved(r, &fakeUnits{}, dir, nil)
	s, err := b.Snapshot(Selection{})
	require.NoError(t, err)
	require.NoError(t, b.Apply(s, false))
	r.gone = map[int]bool{7: true}
	r.links = r.links[:1]
	require.NoError(t, b.Apply(s, false), "re-apply skips the vanished link")
	require.Empty(t, b.Restore(s))
	require.True(t, r.links[0].DefaultRoute)
}

// Review I4: with Ghostline's drop-in still in place, links whose
// DefaultRoute is off were turned off by Ghostline; the original is on.
func TestResolved_SnapshotNeverRecordsOwnDefaultRoute(t *testing.T) {
	dir := t.TempDir()
	r := &fakeResolved{links: []model.ResolvedLink{eth0()}}
	b := newResolved(r, &fakeUnits{}, dir, nil)
	s, err := b.Snapshot(Selection{})
	require.NoError(t, err)
	require.NoError(t, b.Apply(s, false))
	again, err := b.Snapshot(Selection{})
	require.NoError(t, err)
	require.True(t, again.Linux.ResolvedLinks[0].DefaultRoute)
}
