package sysdns

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"slices"

	"github.com/hashcott/ghostline/internal/model"
	"github.com/hashcott/ghostline/internal/netwatch"
)

// marker starts every file Ghostline writes, so it only ever removes its own.
const marker = "# Generated by Ghostline"

const resolvedUnit = "systemd-resolved.service"

// resolvedBackend points systemd-resolved at Ghostline with a runtime
// drop-in (gone at reboot) and stops the links' own servers from also
// answering (DefaultRoute off).
type resolvedBackend struct {
	api    resolvedAPI
	units  unitAPI
	dropIn string
	watch  netwatch.WatchFunc
}

func newResolved(api resolvedAPI, units unitAPI, dropInDir string, watch netwatch.WatchFunc) Backend {
	return &resolvedBackend{api: api, units: units, dropIn: filepath.Join(dropInDir, "ghostline.conf"), watch: watch}
}

func (b *resolvedBackend) Name() string { return "resolved" }

func (b *resolvedBackend) Snapshot(Selection) (Snapshot, error) {
	links, err := b.api.Links()
	if err != nil {
		return Snapshot{}, err
	}
	servers := []string{}
	for _, l := range links {
		for _, s := range l.Servers {
			if !slices.Contains(servers, s) {
				servers = append(servers, s)
			}
		}
	}
	return Snapshot{Backend: b.Name(), Linux: &model.LinuxDNS{ResolvedLinks: links, Servers: notLoopback(servers)}}, nil
}

func dropInContent(v6 bool) []byte {
	dns := "127.0.0.1"
	if v6 {
		dns += " ::1"
	}
	return []byte(marker + "\n[Resolve]\nDNS=" + dns + "\nDomains=~.\n")
}

func (b *resolvedBackend) Apply(s Snapshot, v6 bool) error {
	if err := os.MkdirAll(filepath.Dir(b.dropIn), 0o755); err != nil {
		return err
	}
	if err := writeAtomic(b.dropIn, dropInContent(v6), 0o644); err != nil {
		return err
	}
	if err := b.units.Reload(resolvedUnit); err != nil {
		return err
	}
	var errs []error
	if s.Linux != nil {
		for _, l := range s.Linux.ResolvedLinks {
			errs = append(errs, b.api.SetDefaultRoute(l.IfIndex, false))
		}
	}
	return errors.Join(errs...)
}

func (b *resolvedBackend) haveDropIn() bool {
	got, err := os.ReadFile(b.dropIn)
	return err == nil && bytes.HasPrefix(got, []byte(marker))
}

// Reconcile records links that appeared and finds links whose
// DefaultRoute came back (networkd pushes it again); a missing drop-in
// means everything needs applying.
func (b *resolvedBackend) Reconcile(s Snapshot, _ Selection) (Snapshot, Snapshot, []Change, error) {
	links, err := b.api.Links()
	if err != nil || s.Linux == nil {
		return s, Snapshot{}, nil, err
	}
	next := s
	lin := *s.Linux
	lin.ResolvedLinks = slices.Clone(s.Linux.ResolvedLinks)
	next.Linux = &lin
	known := map[int]bool{}
	for _, l := range lin.ResolvedLinks {
		known[l.IfIndex] = true
	}
	var changes []Change
	for _, l := range links {
		switch {
		case !known[l.IfIndex]:
			lin.ResolvedLinks = append(lin.ResolvedLinks, l)
			changes = append(changes, Change{Target: l.Name})
		case l.DefaultRoute:
			changes = append(changes, Change{Target: l.Name})
		}
	}
	if !b.haveDropIn() && len(changes) == 0 {
		changes = append(changes, Change{Target: "systemd-resolved"})
	}
	if len(changes) == 0 {
		return s, Snapshot{}, nil, nil
	}
	return next, next, changes, nil
}

// StillOurs keeps s while Ghostline's drop-in is in place.
func (b *resolvedBackend) StillOurs(s Snapshot) Snapshot {
	if b.haveDropIn() {
		return s
	}
	return Snapshot{}
}

func (b *resolvedBackend) Restore(s Snapshot) []RestoreError {
	var out []RestoreError
	if err := b.removeDropIn(); err != nil {
		out = append(out, RestoreError{Target: "systemd-resolved", Err: err})
	}
	if s.Linux != nil {
		for _, l := range s.Linux.ResolvedLinks {
			if err := b.api.SetDefaultRoute(l.IfIndex, l.DefaultRoute); err != nil {
				out = append(out, RestoreError{Target: l.Name, Err: err})
			}
		}
	}
	return out
}

// removeDropIn deletes Ghostline's drop-in (if any) and reloads resolved.
func (b *resolvedBackend) removeDropIn() error {
	if !b.haveDropIn() {
		return nil
	}
	if err := os.Remove(b.dropIn); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}
	return b.units.Reload(resolvedUnit)
}

func (b *resolvedBackend) RestoreDefault() error { return b.removeDropIn() }

func (b *resolvedBackend) Flush() error { return b.api.FlushCaches() }

func (b *resolvedBackend) Watch(onChange func()) (func(), error) {
	if b.watch == nil {
		return b.api.Watch(onChange)
	}
	return netwatch.Combine(b.api.Watch, b.watch)(onChange)
}

func (b *resolvedBackend) Info() Info {
	return Info{Backend: b.Name(), Chain: "systemd-resolved", Interfaces: []string{}}
}

// writeAtomic writes path through a temporary file and a rename.
func writeAtomic(path string, data []byte, mode os.FileMode) error {
	tmp := path + ".ghostline.tmp"
	if err := os.WriteFile(tmp, data, mode); err != nil {
		return err
	}
	if err := os.Chmod(tmp, mode); err != nil {
		os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		os.Remove(tmp)
		return err
	}
	return nil
}
