// Code generated by tools/genrpc; DO NOT EDIT.

package client

import (
	"context"
	"github.com/hashcott/ghostline/internal/app"
	"github.com/hashcott/ghostline/internal/backup"
	"github.com/hashcott/ghostline/internal/certstore"
	"github.com/hashcott/ghostline/internal/cfscan"
	"github.com/hashcott/ghostline/internal/dpi"
	"github.com/hashcott/ghostline/internal/engine"
	"github.com/hashcott/ghostline/internal/lookup"
	"github.com/hashcott/ghostline/internal/probe"
	"github.com/hashcott/ghostline/internal/proxy"
	"github.com/hashcott/ghostline/internal/rules"
	"github.com/hashcott/ghostline/internal/rules/lists"
	"github.com/hashcott/ghostline/internal/stamps"
	"github.com/hashcott/ghostline/internal/store"
	"github.com/hashcott/ghostline/internal/sysdns"
	"github.com/wailsapp/wails/v3/pkg/application"
)

// Binding IDs: each method answers the ID Wails gives app.Service's.
func init() {
	application.RegisterBindingMethodID((*Service).AckFakeSNIWarning, 4079707157)
	application.RegisterBindingMethodID((*Service).AddList, 925504398)
	application.RegisterBindingMethodID((*Service).AddScannedServers, 3565303002)
	application.RegisterBindingMethodID((*Service).AddServers, 4130371842)
	application.RegisterBindingMethodID((*Service).AdvancedResults, 1912922961)
	application.RegisterBindingMethodID((*Service).AnswerSysProxyOverride, 824392742)
	application.RegisterBindingMethodID((*Service).AppInfo, 3747507194)
	application.RegisterBindingMethodID((*Service).ApplyImport, 1497242288)
	application.RegisterBindingMethodID((*Service).CFSuggestDomains, 2905544505)
	application.RegisterBindingMethodID((*Service).CancelAdvancedScan, 1133964998)
	application.RegisterBindingMethodID((*Service).CancelAutotune, 657798692)
	application.RegisterBindingMethodID((*Service).CancelCFScan, 1305802585)
	application.RegisterBindingMethodID((*Service).CancelConnect, 3702584373)
	application.RegisterBindingMethodID((*Service).CancelScan, 3097932)
	application.RegisterBindingMethodID((*Service).Catalog, 3755031066)
	application.RegisterBindingMethodID((*Service).CheckServer, 651468430)
	application.RegisterBindingMethodID((*Service).CheckUpdateNow, 3677662544)
	application.RegisterBindingMethodID((*Service).ClearFragCache, 1338970638)
	application.RegisterBindingMethodID((*Service).CloseSetupPage, 1785012837)
	application.RegisterBindingMethodID((*Service).Connect, 2539050987)
	application.RegisterBindingMethodID((*Service).CountScanServers, 164162785)
	application.RegisterBindingMethodID((*Service).CreateCFRules, 1469676265)
	application.RegisterBindingMethodID((*Service).DPIEngineDir, 3287260203)
	application.RegisterBindingMethodID((*Service).DPIStrategies, 995292599)
	application.RegisterBindingMethodID((*Service).DecodeStamps, 1897304945)
	application.RegisterBindingMethodID((*Service).DefaultLookupSources, 3708316264)
	application.RegisterBindingMethodID((*Service).DeleteList, 1648317212)
	application.RegisterBindingMethodID((*Service).DeleteUpstreamProxy, 3136894903)
	application.RegisterBindingMethodID((*Service).Disconnect, 795153741)
	application.RegisterBindingMethodID((*Service).DismissWarning, 3448665231)
	application.RegisterBindingMethodID((*Service).EncodeStamp, 3324832188)
	application.RegisterBindingMethodID((*Service).Explain, 4164369326)
	application.RegisterBindingMethodID((*Service).ExportAdvancedCSV, 3916804869)
	application.RegisterBindingMethodID((*Service).ExportSettings, 1800124184)
	application.RegisterBindingMethodID((*Service).GetCFView, 2373241057)
	application.RegisterBindingMethodID((*Service).GetDPIAutoHostlist, 540630337)
	application.RegisterBindingMethodID((*Service).GetDPIBlacklist, 2098999863)
	application.RegisterBindingMethodID((*Service).GetDeviceInfo, 1619967979)
	application.RegisterBindingMethodID((*Service).GetFakeSNIView, 1449416301)
	application.RegisterBindingMethodID((*Service).GetFragCache, 2469803425)
	application.RegisterBindingMethodID((*Service).GetLANInfo, 2624993672)
	application.RegisterBindingMethodID((*Service).GetLogs, 1093386938)
	application.RegisterBindingMethodID((*Service).GetProxyConns, 969489238)
	application.RegisterBindingMethodID((*Service).GetProxyStats, 1462836650)
	application.RegisterBindingMethodID((*Service).GetQR, 2021338198)
	application.RegisterBindingMethodID((*Service).GetQueries, 3315320319)
	application.RegisterBindingMethodID((*Service).GetRules, 2138976220)
	application.RegisterBindingMethodID((*Service).GetSettings, 489716924)
	application.RegisterBindingMethodID((*Service).GetSnapshot, 707042289)
	application.RegisterBindingMethodID((*Service).ISPResolvers, 2476748652)
	application.RegisterBindingMethodID((*Service).LANDNSClients, 1438181071)
	application.RegisterBindingMethodID((*Service).ListAdapters, 3784046047)
	application.RegisterBindingMethodID((*Service).ListCerts, 3139331874)
	application.RegisterBindingMethodID((*Service).ListServers, 1800138261)
	application.RegisterBindingMethodID((*Service).Lookup, 1132046225)
	application.RegisterBindingMethodID((*Service).LookupTypes, 1975301726)
	application.RegisterBindingMethodID((*Service).MarkNetworkChecked, 4284519977)
	application.RegisterBindingMethodID((*Service).MoveList, 3905155114)
	application.RegisterBindingMethodID((*Service).OpenSetupPage, 2369120791)
	application.RegisterBindingMethodID((*Service).PreviewDPIArgs, 1895220961)
	application.RegisterBindingMethodID((*Service).PreviewImport, 1769623048)
	application.RegisterBindingMethodID((*Service).ProbeNow, 3735268141)
	application.RegisterBindingMethodID((*Service).RecheckCF, 1148860931)
	application.RegisterBindingMethodID((*Service).RefreshList, 519137862)
	application.RegisterBindingMethodID((*Service).RemoveAllCerts, 2784068929)
	application.RegisterBindingMethodID((*Service).RemoveCustomServer, 4273099491)
	application.RegisterBindingMethodID((*Service).RemoveLANCA, 1863071482)
	application.RegisterBindingMethodID((*Service).ResetLANCA, 2275867613)
	application.RegisterBindingMethodID((*Service).RestoreDNSNow, 2705699194)
	application.RegisterBindingMethodID((*Service).RestoreSystemProxy, 432049994)
	application.RegisterBindingMethodID((*Service).RetryCertRemoval, 1075076607)
	application.RegisterBindingMethodID((*Service).RetryFakeSNI, 1057487630)
	application.RegisterBindingMethodID((*Service).RetryProxy, 1163466545)
	application.RegisterBindingMethodID((*Service).RetryZapret2, 2380369949)
	application.RegisterBindingMethodID((*Service).SaveDPIAutoHostlist, 1018005824)
	application.RegisterBindingMethodID((*Service).SaveDPIBlacklist, 1367729508)
	application.RegisterBindingMethodID((*Service).SaveDeviceFiles, 1887833571)
	application.RegisterBindingMethodID((*Service).SaveRulesTable, 390681375)
	application.RegisterBindingMethodID((*Service).SaveRulesText, 1940641918)
	application.RegisterBindingMethodID((*Service).SaveSettings, 3355123671)
	application.RegisterBindingMethodID((*Service).SaveUpstreamProxy, 1881531961)
	application.RegisterBindingMethodID((*Service).ScanAll, 2244859853)
	application.RegisterBindingMethodID((*Service).SetDNSServer, 2015893111)
	application.RegisterBindingMethodID((*Service).SetDPIEnabled, 991973209)
	application.RegisterBindingMethodID((*Service).SetFakeSNI, 3117162048)
	application.RegisterBindingMethodID((*Service).SetIOSSSID, 1202066449)
	application.RegisterBindingMethodID((*Service).SetListTrustedForSNI, 2975602805)
	application.RegisterBindingMethodID((*Service).SetMode, 2398091530)
	application.RegisterBindingMethodID((*Service).SetPinned, 3815583927)
	application.RegisterBindingMethodID((*Service).SetPinnedMany, 3303438448)
	application.RegisterBindingMethodID((*Service).SetProxyEnabled, 2917345384)
	application.RegisterBindingMethodID((*Service).SetQueryLog, 1068579019)
	application.RegisterBindingMethodID((*Service).StampFromURL, 2431372379)
	application.RegisterBindingMethodID((*Service).StartAdvancedScan, 3867606322)
	application.RegisterBindingMethodID((*Service).StartAutotune, 1763005864)
	application.RegisterBindingMethodID((*Service).StartCFScan, 3945714453)
	application.RegisterBindingMethodID((*Service).StopConflictingService, 3805516582)
	application.RegisterBindingMethodID((*Service).TestUpstreamProxy, 1421704818)
	application.RegisterBindingMethodID((*Service).UpdateList, 75098978)
	application.RegisterBindingMethodID((*Service).UseOnlyServer, 2807799011)
}

func (s *Service) AckFakeSNIWarning() error {
	return s.call(context.Background(), "AckFakeSNIWarning", nil)
}

func (s *Service) AddList(a0 lists.List) (lists.List, error) {
	var r lists.List
	err := s.call(context.Background(), "AddList", &r, a0)
	return r, err
}

func (s *Service) AddScannedServers(a0 []string) (int, error) {
	var r int
	err := s.call(context.Background(), "AddScannedServers", &r, a0)
	return r, err
}

func (s *Service) AddServers(a0 string) (int, []string) {
	var r0 int
	var r1 []string
	err := s.callTuple(context.Background(), "AddServers", []any{&r0, &r1}, a0)
	s.logErr("AddServers", err)
	return r0, r1
}

func (s *Service) AdvancedResults() []app.AdvRow {
	var r []app.AdvRow
	err := s.call(context.Background(), "AdvancedResults", &r)
	s.logErr("AdvancedResults", err)
	return r
}

func (s *Service) AnswerSysProxyOverride(a0 bool) {
	s.logErr("AnswerSysProxyOverride", s.call(context.Background(), "AnswerSysProxyOverride", nil, a0))
}

func (s *Service) AppInfo() app.AppInfo {
	var r app.AppInfo
	err := s.call(context.Background(), "AppInfo", &r)
	s.logErr("AppInfo", err)
	return r
}

func (s *Service) ApplyImport(a0 string, a1 backup.Choices) error {
	return s.call(context.Background(), "ApplyImport", nil, a0, a1)
}

func (s *Service) CFSuggestDomains() []string {
	var r []string
	err := s.call(context.Background(), "CFSuggestDomains", &r)
	s.logErr("CFSuggestDomains", err)
	return r
}

func (s *Service) CancelAdvancedScan() {
	s.logErr("CancelAdvancedScan", s.call(context.Background(), "CancelAdvancedScan", nil))
}

func (s *Service) CancelAutotune() {
	s.logErr("CancelAutotune", s.call(context.Background(), "CancelAutotune", nil))
}

func (s *Service) CancelCFScan() {
	s.logErr("CancelCFScan", s.call(context.Background(), "CancelCFScan", nil))
}

func (s *Service) CancelConnect() {
	s.logErr("CancelConnect", s.call(context.Background(), "CancelConnect", nil))
}

func (s *Service) CancelScan() {
	s.logErr("CancelScan", s.call(context.Background(), "CancelScan", nil))
}

func (s *Service) Catalog() []lists.CatalogItem {
	var r []lists.CatalogItem
	err := s.call(context.Background(), "Catalog", &r)
	s.logErr("Catalog", err)
	return r
}

func (s *Service) CheckServer(a0 string) (app.ServerRow, error) {
	var r app.ServerRow
	err := s.call(context.Background(), "CheckServer", &r, a0)
	return r, err
}

func (s *Service) CheckUpdateNow() (app.UpdateCheck, error) {
	var r app.UpdateCheck
	err := s.call(context.Background(), "CheckUpdateNow", &r)
	return r, err
}

func (s *Service) ClearFragCache(a0 string) error {
	return s.call(context.Background(), "ClearFragCache", nil, a0)
}

func (s *Service) CloseSetupPage() error {
	return s.call(context.Background(), "CloseSetupPage", nil)
}

func (s *Service) Connect() error {
	return s.call(context.Background(), "Connect", nil)
}

func (s *Service) CountScanServers(a0 app.ServerFilter) int {
	var r int
	err := s.call(context.Background(), "CountScanServers", &r, a0)
	s.logErr("CountScanServers", err)
	return r
}

func (s *Service) CreateCFRules(a0 []string, a1 []string) []rules.LineError {
	var r []rules.LineError
	err := s.call(context.Background(), "CreateCFRules", &r, a0, a1)
	s.logErr("CreateCFRules", err)
	return r
}

func (s *Service) DPIEngineDir(a0 string) string {
	var r string
	err := s.call(context.Background(), "DPIEngineDir", &r, a0)
	s.logErr("DPIEngineDir", err)
	return r
}

func (s *Service) DPIStrategies(a0 string) ([]dpi.Strategy, error) {
	var r []dpi.Strategy
	err := s.call(context.Background(), "DPIStrategies", &r, a0)
	return r, err
}

func (s *Service) DecodeStamps(a0 string) []app.StampCard {
	var r []app.StampCard
	err := s.call(context.Background(), "DecodeStamps", &r, a0)
	s.logErr("DecodeStamps", err)
	return r
}

func (s *Service) DefaultLookupSources() []lookup.Source {
	var r []lookup.Source
	err := s.call(context.Background(), "DefaultLookupSources", &r)
	s.logErr("DefaultLookupSources", err)
	return r
}

func (s *Service) DeleteList(a0 string) error {
	return s.call(context.Background(), "DeleteList", nil, a0)
}

func (s *Service) DeleteUpstreamProxy(a0 string) error {
	return s.call(context.Background(), "DeleteUpstreamProxy", nil, a0)
}

func (s *Service) Disconnect() error {
	return s.call(context.Background(), "Disconnect", nil)
}

func (s *Service) DismissWarning(a0 string) {
	s.logErr("DismissWarning", s.call(context.Background(), "DismissWarning", nil, a0))
}

func (s *Service) EncodeStamp(a0 stamps.Fields) (string, error) {
	var r string
	err := s.call(context.Background(), "EncodeStamp", &r, a0)
	return r, err
}

func (s *Service) Explain(a0 string) rules.Decision {
	var r rules.Decision
	err := s.call(context.Background(), "Explain", &r, a0)
	s.logErr("Explain", err)
	return r
}

func (s *Service) ExportAdvancedCSV(ctx context.Context) error {
	return s.call(ctx, "ExportAdvancedCSV", nil)
}

func (s *Service) ExportSettings(ctx context.Context, a0 []string) error {
	return s.call(ctx, "ExportSettings", nil, a0)
}

func (s *Service) GetCFView() app.CFView {
	var r app.CFView
	err := s.call(context.Background(), "GetCFView", &r)
	s.logErr("GetCFView", err)
	return r
}

func (s *Service) GetDPIAutoHostlist() ([]string, error) {
	var r []string
	err := s.call(context.Background(), "GetDPIAutoHostlist", &r)
	return r, err
}

func (s *Service) GetDPIBlacklist() (string, error) {
	var r string
	err := s.call(context.Background(), "GetDPIBlacklist", &r)
	return r, err
}

func (s *Service) GetDeviceInfo() app.DeviceInfo {
	var r app.DeviceInfo
	err := s.call(context.Background(), "GetDeviceInfo", &r)
	s.logErr("GetDeviceInfo", err)
	return r
}

func (s *Service) GetFakeSNIView() app.FakeSNIView {
	var r app.FakeSNIView
	err := s.call(context.Background(), "GetFakeSNIView", &r)
	s.logErr("GetFakeSNIView", err)
	return r
}

func (s *Service) GetFragCache() []string {
	var r []string
	err := s.call(context.Background(), "GetFragCache", &r)
	s.logErr("GetFragCache", err)
	return r
}

func (s *Service) GetLANInfo() app.LANInfo {
	var r app.LANInfo
	err := s.call(context.Background(), "GetLANInfo", &r)
	s.logErr("GetLANInfo", err)
	return r
}

func (s *Service) GetLogs() []app.LogEvent {
	var r []app.LogEvent
	err := s.call(context.Background(), "GetLogs", &r)
	s.logErr("GetLogs", err)
	return r
}

func (s *Service) GetProxyConns() []proxy.ConnEvent {
	var r []proxy.ConnEvent
	err := s.call(context.Background(), "GetProxyConns", &r)
	s.logErr("GetProxyConns", err)
	return r
}

func (s *Service) GetProxyStats() proxy.Stats {
	var r proxy.Stats
	err := s.call(context.Background(), "GetProxyStats", &r)
	s.logErr("GetProxyStats", err)
	return r
}

func (s *Service) GetQR(a0 string) ([][]bool, error) {
	var r [][]bool
	err := s.call(context.Background(), "GetQR", &r, a0)
	return r, err
}

func (s *Service) GetQueries() []engine.QueryEvent {
	var r []engine.QueryEvent
	err := s.call(context.Background(), "GetQueries", &r)
	s.logErr("GetQueries", err)
	return r
}

func (s *Service) GetRules() app.RulesView {
	var r app.RulesView
	err := s.call(context.Background(), "GetRules", &r)
	s.logErr("GetRules", err)
	return r
}

func (s *Service) GetSettings() store.Settings {
	var r store.Settings
	err := s.call(context.Background(), "GetSettings", &r)
	s.logErr("GetSettings", err)
	return r
}

func (s *Service) ISPResolvers() []string {
	var r []string
	err := s.call(context.Background(), "ISPResolvers", &r)
	s.logErr("ISPResolvers", err)
	return r
}

func (s *Service) LANDNSClients() int {
	var r int
	err := s.call(context.Background(), "LANDNSClients", &r)
	s.logErr("LANDNSClients", err)
	return r
}

func (s *Service) ListAdapters() []sysdns.Adapter {
	var r []sysdns.Adapter
	err := s.call(context.Background(), "ListAdapters", &r)
	s.logErr("ListAdapters", err)
	return r
}

func (s *Service) ListCerts() ([]certstore.Cert, error) {
	var r []certstore.Cert
	err := s.call(context.Background(), "ListCerts", &r)
	return r, err
}

func (s *Service) ListServers() []app.ServerRow {
	var r []app.ServerRow
	err := s.call(context.Background(), "ListServers", &r)
	s.logErr("ListServers", err)
	return r
}

func (s *Service) Lookup(a0 string, a1 string, a2 []lookup.Source) (app.LookupResult, error) {
	var r app.LookupResult
	err := s.call(context.Background(), "Lookup", &r, a0, a1, a2)
	return r, err
}

func (s *Service) LookupTypes() []string {
	var r []string
	err := s.call(context.Background(), "LookupTypes", &r)
	s.logErr("LookupTypes", err)
	return r
}

func (s *Service) MarkNetworkChecked() error {
	return s.call(context.Background(), "MarkNetworkChecked", nil)
}

func (s *Service) MoveList(a0 string, a1 int) error {
	return s.call(context.Background(), "MoveList", nil, a0, a1)
}

func (s *Service) OpenSetupPage() (string, error) {
	var r string
	err := s.call(context.Background(), "OpenSetupPage", &r)
	return r, err
}

func (s *Service) PreviewDPIArgs(a0 string, a1 string, a2 string, a3 string, a4 bool) ([]string, error) {
	var r []string
	err := s.call(context.Background(), "PreviewDPIArgs", &r, a0, a1, a2, a3, a4)
	return r, err
}

func (s *Service) PreviewImport(ctx context.Context) (app.ImportPreview, error) {
	var r app.ImportPreview
	err := s.call(ctx, "PreviewImport", &r)
	return r, err
}

func (s *Service) ProbeNow() []probe.Result {
	var r []probe.Result
	err := s.call(context.Background(), "ProbeNow", &r)
	s.logErr("ProbeNow", err)
	return r
}

func (s *Service) RecheckCF(a0 []string) ([]cfscan.Result, error) {
	var r []cfscan.Result
	err := s.call(context.Background(), "RecheckCF", &r, a0)
	return r, err
}

func (s *Service) RefreshList(a0 string) error {
	return s.call(context.Background(), "RefreshList", nil, a0)
}

func (s *Service) RemoveAllCerts() error {
	return s.call(context.Background(), "RemoveAllCerts", nil)
}

func (s *Service) RemoveCustomServer(a0 string) error {
	return s.call(context.Background(), "RemoveCustomServer", nil, a0)
}

func (s *Service) RemoveLANCA() error {
	return s.call(context.Background(), "RemoveLANCA", nil)
}

func (s *Service) ResetLANCA() error {
	return s.call(context.Background(), "ResetLANCA", nil)
}

func (s *Service) RestoreDNSNow() error {
	return s.call(context.Background(), "RestoreDNSNow", nil)
}

func (s *Service) RestoreSystemProxy() error {
	return s.call(context.Background(), "RestoreSystemProxy", nil)
}

func (s *Service) RetryCertRemoval() error {
	return s.call(context.Background(), "RetryCertRemoval", nil)
}

func (s *Service) RetryFakeSNI() error {
	return s.call(context.Background(), "RetryFakeSNI", nil)
}

func (s *Service) RetryProxy() error {
	return s.call(context.Background(), "RetryProxy", nil)
}

func (s *Service) RetryZapret2() error {
	return s.call(context.Background(), "RetryZapret2", nil)
}

func (s *Service) SaveDPIAutoHostlist(a0 []string) error {
	return s.call(context.Background(), "SaveDPIAutoHostlist", nil, a0)
}

func (s *Service) SaveDPIBlacklist(a0 string) error {
	return s.call(context.Background(), "SaveDPIBlacklist", nil, a0)
}

func (s *Service) SaveDeviceFiles(ctx context.Context) error {
	return s.call(ctx, "SaveDeviceFiles", nil)
}

func (s *Service) SaveRulesTable(a0 []rules.Rule) []rules.LineError {
	var r []rules.LineError
	err := s.call(context.Background(), "SaveRulesTable", &r, a0)
	s.logErr("SaveRulesTable", err)
	return r
}

func (s *Service) SaveRulesText(a0 string) []rules.LineError {
	var r []rules.LineError
	err := s.call(context.Background(), "SaveRulesText", &r, a0)
	s.logErr("SaveRulesText", err)
	return r
}

func (s *Service) SaveSettings(a0 store.Settings) error {
	return s.call(context.Background(), "SaveSettings", nil, a0)
}

func (s *Service) SaveUpstreamProxy(a0 store.UpstreamProxy, a1 string) error {
	return s.call(context.Background(), "SaveUpstreamProxy", nil, a0, a1)
}

func (s *Service) ScanAll() error {
	return s.call(context.Background(), "ScanAll", nil)
}

func (s *Service) SetDNSServer(a0 bool, a1 bool, a2 int) error {
	return s.call(context.Background(), "SetDNSServer", nil, a0, a1, a2)
}

func (s *Service) SetDPIEnabled(a0 bool) error {
	return s.call(context.Background(), "SetDPIEnabled", nil, a0)
}

func (s *Service) SetFakeSNI(a0 bool) error {
	return s.call(context.Background(), "SetFakeSNI", nil, a0)
}

func (s *Service) SetIOSSSID(a0 string) error {
	return s.call(context.Background(), "SetIOSSSID", nil, a0)
}

func (s *Service) SetListTrustedForSNI(a0 string, a1 bool) error {
	return s.call(context.Background(), "SetListTrustedForSNI", nil, a0, a1)
}

func (s *Service) SetPinned(a0 string, a1 bool) error {
	return s.call(context.Background(), "SetPinned", nil, a0, a1)
}

func (s *Service) SetPinnedMany(a0 []string, a1 bool) error {
	return s.call(context.Background(), "SetPinnedMany", nil, a0, a1)
}

func (s *Service) SetProxyEnabled(a0 bool) error {
	return s.call(context.Background(), "SetProxyEnabled", nil, a0)
}

func (s *Service) SetQueryLog(a0 bool) {
	s.logErr("SetQueryLog", s.call(context.Background(), "SetQueryLog", nil, a0))
}

func (s *Service) StampFromURL(a0 string, a1 string) (stamps.Fields, error) {
	var r stamps.Fields
	err := s.call(context.Background(), "StampFromURL", &r, a0, a1)
	return r, err
}

func (s *Service) StartAdvancedScan(a0 app.AdvScanRequest) (app.AdvScanStart, error) {
	var r app.AdvScanStart
	err := s.call(context.Background(), "StartAdvancedScan", &r, a0)
	return r, err
}

func (s *Service) StartAutotune() error {
	return s.call(context.Background(), "StartAutotune", nil)
}

func (s *Service) StartCFScan() error {
	return s.call(context.Background(), "StartCFScan", nil)
}

func (s *Service) StopConflictingService(a0 string) error {
	return s.call(context.Background(), "StopConflictingService", nil, a0)
}

func (s *Service) TestUpstreamProxy(a0 string) error {
	return s.call(context.Background(), "TestUpstreamProxy", nil, a0)
}

func (s *Service) UpdateList(a0 lists.List) error {
	return s.call(context.Background(), "UpdateList", nil, a0)
}

func (s *Service) UseOnlyServer(a0 string) error {
	return s.call(context.Background(), "UseOnlyServer", nil, a0)
}
